using IWClimateControl;
using StardewValley;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IW_ClimateControl
{
    /// <summary>
    /// Calculates weather for tomorrow.
    /// </summary>
    internal class WeatherSlotMachine
    {
        /// <summary>
        /// Generates weather based on config values.
        /// </summary>
        /// <param name="currentDate">Generated by Stardew Valley.</param>
        /// <param name="weatherChances">This model's probability profile.</param>
        /// <param name="api">Framework API.</param>
        /// <param name="weatherJackpot">The successful weather type for tomorrow.</param>
        /// <param name="diceRoll">The dice roll of the successful weather type.</param>
        /// <param name="odds">The probability of the successful weather type.</param>
        public static void GenerateWeather(WorldDate currentDate, ModelDefinition weatherChances, IWAPI api, out IWAPI.WeatherType weatherJackpot, out double diceRoll, out double odds)
        {
            // Initialize
            Season modelSeason = new();
            IWAPI.SeasonType currentSeason = Enum.Parse<IWAPI.SeasonType>(currentDate.Season);

            // Consider only the relevant season.
            switch (currentSeason)
            {
                case IWAPI.SeasonType.spring:
                    modelSeason = weatherChances.Spring;
                    break;
                case IWAPI.SeasonType.summer:
                    modelSeason = weatherChances.Summer;
                    break;
                case IWAPI.SeasonType.fall:
                    modelSeason = weatherChances.Fall;
                    break;
                case IWAPI.SeasonType.winter:
                    modelSeason = weatherChances.Winter;
                    break;
            }
        }

        /// <summary>
        /// Chooses weather for tomorrow.
        /// </summary>
        /// <param name="modelSeason">The likelihood of each weather type.</param>
        /// <param name="api">Framework API</param>
        /// <param name="weatherJackpot">The successful weather for tomorrow.</param>
        /// <param name="diceRoll">The dice roll of the successful weather type.</param>
        /// <param name="odds">The probability of the successful weather type.</param>
        private static void ChooseWeather(Season modelSeason, IWAPI api, out IWAPI.WeatherType weatherJackpot, out double diceRoll, out double odds)
        {
            // Default values
            diceRoll = 1.0;
            odds = 0.0;
            weatherJackpot = IWAPI.WeatherType.sunny;

            // List of dicerolls for each weather type.
            List<Tuple<bool, double>> weatherRolls = new();

            // Flip a coin for each type of weather.
            weatherRolls.Add(FlipCoin(modelSeason.Storm.Mid, api));
            weatherRolls.Add(FlipCoin(modelSeason.Rain.Mid, api));
            weatherRolls.Add(FlipCoin(modelSeason.Wind.Mid, api));
            weatherRolls.Add(FlipCoin(modelSeason.Snow.Mid, api));

            // Find the weather with the lowest successful dice-roll.
            for (int i = 0; i < weatherRolls.Count; i++)
            {
                if ((weatherRolls[i].Item1 == true) && weatherRolls[i].Item2 <= diceRoll)
                {
                    diceRoll = weatherRolls[i].Item2;
                    switch (i)
                    {
                        case 0:
                            weatherJackpot = IWAPI.WeatherType.storming;
                            odds = modelSeason.Storm.Mid;
                            break;
                        case 1:
                            weatherJackpot = IWAPI.WeatherType.raining;
                            odds = modelSeason.Rain.Mid;
                            break;
                        case 2:
                            weatherJackpot = IWAPI.WeatherType.windy;
                            odds = modelSeason.Wind.Mid;
                            break;
                        case 3:
                            weatherJackpot = IWAPI.WeatherType.snowing;
                            odds = modelSeason.Snow.Mid;
                            break;
                    }
                }
            }
        }

        /// <summary>
        /// Roll a random number to determine if the weather changes.
        /// </summary>
        /// <param name="chance">Likelihood of a change.</param>
        /// <param name="api">Framework API.</param>
        /// <returns>Tuple: The successful weather type and the value of the dice roll.</returns>
        private static Tuple<bool, double> FlipCoin(double chance, IWAPI api)
        {
            // If dice roll lands within the percentage, permit the change.
            // Otherwise, deny it. Smaller percentages have narrower
            // windows, corresponding to a lower likelihood of change.
            bool weatherBool = false;
            double diceRoll = api.RollTheDice();
            if ((0.01 * chance) >= diceRoll)
                weatherBool = true;
            return new Tuple<bool, double>(weatherBool, diceRoll);
        }

        /// <summary>
        /// Check if tomorrow's weather is allowed to change.
        /// </summary>
        /// <param name="currentDate">Generated by Stardew Valley.</param>
        /// <param name="canChange">Can the weather be changed?</param>
        /// <param name="reason">If not, why not?</param>
        public static void CheckCanChange(WorldDate currentDate, out bool canChange, out string reason)
        {
            // Initialize.
            canChange = true;
            reason = "";

            // Check possibilities
            switch (currentDate.TotalDays)
            {
                case 1:
                case 2:
                case 3:
                case 4:
                    // Too early in game.
                    canChange = false;
                    reason = "the player has played too few days on this save.";
                    break;
                default:
                    switch (Game1.weatherForTomorrow)
                    {
                        case (int)IWAPI.WeatherType.festival:
                            // Festival tomorrow.
                            canChange = false;
                            reason = "tomorrow is a festival.";
                            break;
                        case (int)IWAPI.WeatherType.wedding:
                            // Wedding tomorrow.
                            canChange = false;
                            reason = "tomorrow is your wedding. Congratulations!";
                            break;
                        default:
                            switch (currentDate.DayOfMonth)
                            {
                                case 28:
                                    // First day of a season is always Sunny.
                                    canChange = false;
                                    reason = "tomorrow is the first day of the season and it is always sunny.";
                                    break;
                                default:
                                    switch (Enum.Parse<IWAPI.SeasonType>(currentDate.Season))
                                    {
                                        case IWAPI.SeasonType.summer:
                                            if ((currentDate.DayOfMonth + 1) % 13 == 0)
                                            {
                                                // Summer 13 and 26 always storm.
                                                canChange = false;
                                                reason = "tomorrow is a Summer day and is hardcoded to storm.";
                                            }
                                            break;
                                    }
                                    break;
                            }
                            break;
                    }
                    break;
            }
        }
    }
}
