using IWClimateControl;
using StardewValley;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IW_ClimateControl
{
    /// <summary>
    /// Calculates weather for tomorrow.
    /// </summary>
    internal class WeatherSlotMachine
    {
        /// <summary>
        /// Generates weather based on config values.
        /// </summary>
        /// <param name="currentDate">Generated by Stardew Valley.</param>
        /// <param name="weatherChances">This model's probability profile.</param>
        /// <param name="api">Framework API.</param>
        /// <param name="weatherJackpot">The successful weather type for tomorrow.</param>
        /// <param name="diceRoll">The dice roll of the successful weather type.</param>
        /// <param name="odds">The probability of the successful weather type.</param>
        public static void GenerateWeather(WorldDate currentDate, ModelDefinition weatherChances, IWAPI api, out IWAPI.WeatherType weatherJackpot, out double diceRoll, out double odds)
        {
            // Initialize
            Season modelSeason = new();
            IWAPI.SeasonType currentSeason = Enum.Parse<IWAPI.SeasonType>(currentDate.Season);

            // Consider only the relevant season.
            switch (currentSeason)
            {
                case IWAPI.SeasonType.spring:
                    modelSeason = weatherChances.Spring;
                    break;
                case IWAPI.SeasonType.summer:
                    modelSeason = weatherChances.Summer;
                    break;
                case IWAPI.SeasonType.fall:
                    modelSeason = weatherChances.Fall;
                    break;
                case IWAPI.SeasonType.winter:
                    modelSeason = weatherChances.Winter;
                    break;
            }

            // Flip a coin for each type of weather.
            WeatherCoin.FlipCoin(modelSeason.Storm.Mid, api, out bool stormBool, out double stormRoll);
            WeatherCoin.FlipCoin(modelSeason.Rain.Mid, api, out bool rainBool, out double rainRoll);
            WeatherCoin.FlipCoin(modelSeason.Wind.Mid, api, out bool windBool, out double windRoll);
            WeatherCoin.FlipCoin(modelSeason.Snow.Mid, api, out bool snowBool, out double snowRoll);

            // For now, prioritise storms over rain over wind over snow.
            if (stormBool)
            {
                // Thunderstorms.
                weatherJackpot = IWAPI.WeatherType.storming;
                diceRoll = stormRoll;
                odds = modelSeason.Storm.Mid;
            }
            else if (rainBool)
            {
                // Rainfall.
                weatherJackpot = IWAPI.WeatherType.raining;
                diceRoll = rainRoll;
                odds = modelSeason.Rain.Mid;
            }
            else if (windBool)
            {
                // Windy weather.
                weatherJackpot = IWAPI.WeatherType.windy;
                diceRoll = windRoll;
                odds = modelSeason.Wind.Mid;
            }
            else if (snowBool)
            {
                // Snowfall.
                weatherJackpot = IWAPI.WeatherType.snowing;
                diceRoll = snowRoll;
                odds = modelSeason.Snow.Mid;
            }
            else
            {
                // No winner, so default to Sunny.
                weatherJackpot = IWAPI.WeatherType.sunny;
                diceRoll = 0.0;
                odds = 0.0;
            }
        }

        /// <summary>
        /// Check if tomorrow's weather is allowed to change.
        /// </summary>
        /// <param name="currentDate">Generated by Stardew Valley.</param>
        /// <param name="canChange">Can the weather be changed?</param>
        /// <param name="reason">If not, why not?</param>
        public static void CheckCanChange(WorldDate currentDate, out bool canChange, out string reason)
        {
            // Initialize.
            canChange = true;
            reason = "";

            // Check possibilities
            switch (currentDate.TotalDays)
            {
                case 1:
                case 2:
                case 3:
                case 4:
                    // Too early in game.
                    canChange = false;
                    reason = "the player has played too few days on this save.";
                    break;
                default:
                    switch (Game1.weatherForTomorrow)
                    {
                        case (int)IWAPI.WeatherType.festival:
                            // Festival tomorrow.
                            canChange = false;
                            reason = "tomorrow is a festival.";
                            break;
                        case (int)IWAPI.WeatherType.wedding:
                            // Wedding tomorrow.
                            canChange = false;
                            reason = "tomorrow is your wedding. Congratulations!";
                            break;
                        default:
                            switch (currentDate.DayOfMonth)
                            {
                                case 28:
                                    // First day of a season is always Sunny.
                                    canChange = false;
                                    reason = "tomorrow is the first day of the season and it is always sunny.";
                                    break;
                                default:
                                    switch (Enum.Parse<IWAPI.SeasonType>(currentDate.Season))
                                    {
                                        case IWAPI.SeasonType.summer:
                                            if ((currentDate.DayOfMonth + 1) % 13 == 0)
                                            {
                                                // Summer 13 and 26 always storm.
                                                canChange = false;
                                                reason = "tomorrow is a Summer day and is hardcoded to storm.";
                                            }
                                            break;
                                    }
                                    break;
                            }
                            break;
                    }
                    break;
            }
        }


    }

    /// <summary>
    /// Handles dice rolls for weather changes.
    /// </summary>
    internal class WeatherCoin
    {
        /// <summary>
        /// Roll a random number to determine if the weather changes.
        /// </summary>
        /// <param name="chance">Likelihood of a change.</param>
        /// <param name="api">Framework API.</param>
        /// <param name="weatherBool">Can the weather change?</param>
        /// <param name="diceRoll">Random number output by <see cref="IWAPI.RollTheDice"/></param>
        public static void FlipCoin(double chance, IWAPI api, out bool weatherBool, out double diceRoll)
        {
            // If dice roll lands within the percentage, permit the change.
            // Otherwise, deny it. Smaller percentages have narrower
            // windows, corresponding to a lower likelihood of change.
            weatherBool = false;
            diceRoll = api.RollTheDice();
            if ((0.01 * chance) >= diceRoll)
                weatherBool = true;
        }
    }
}
